import { describe, expect, it } from "vitest";
import { projectHermesMemory, toEntry, visibleCards, type BotMemoryCard } from "../src/memory.js";
import { readFileSync } from "node:fs";
import { entryHash, generatedKo, koLookup } from "../src/knowledge.js";

// Korean display for the "봇 기억" cards: English source stays the source of truth, Korean is looked up by content hash.
describe("봇 기억 카드 한국어 표시", () => {
  const EN = "User speaks in terse Korean imperatives and holds the agent to previously agreed procedures.";
  const KO = "사장님은 짧은 한국어로 지시하고, 이전에 합의한 절차를 지키길 기대한다.";
  const lookup = koLookup({ items: { [entryHash(EN)]: { ko: KO } } });

  it("번역이 있으면 한국어를 보여 주고 영어 원문은 따로 보관한다", () => {
    const e = toEntry(EN, 0, lookup);
    expect(e.text).toBe(KO);
    expect(e.preview.startsWith("사장님은")).toBe(true);
    expect(e.original).toBe(EN);
    expect(e.pending).toBeFalsy();
    expect(e.chars).toBe(Array.from(EN).length); // 글자 수는 실제 파일(영어) 기준
  });

  it("한국어 원문은 그대로, 번역 없는 영어는 원문 + 번역 대기", () => {
    const k = toEntry("사장님은 표를 좋아한다.", 0, lookup);
    expect(k).toMatchObject({ text: "사장님은 표를 좋아한다." });
    expect(k.original).toBeUndefined();
    expect(k.pending).toBeFalsy();
    const u = toEntry("A brand new English fact nobody translated yet.", 1, lookup);
    expect(u.text).toBe("A brand new English fact nobody translated yet.");
    expect(u.original).toBeUndefined();
    expect(u.pending).toBe(true);
    // lookup 없이 부르면 예전과 같다(번역 대기 표시도 없음)
    expect(toEntry(EN, 0)).toMatchObject({ text: EN });
    expect(toEntry(EN, 0).pending).toBeFalsy();
  });

  it("영어 용어가 많이 섞인 한국어 문장은 번역 대상이 아니다(그대로 보여 준다)", () => {
    const k = "academy-homepage(Next.js)는 NAS에서 docker-compose로 서비스: app(port 3080)+cloudflared tunnel+backup 컨테이너.";
    const e = toEntry(k, 0, koLookup({ items: { [entryHash(k)]: { ko: "다른 번역" } } }));
    expect(e.text).toBe(k);
    expect(e.original).toBeUndefined();
    expect(e.pending).toBeFalsy();
  });

  it("비밀값 가림은 한국어·원문 모두에 적용된다", () => {
    const en = "Deploy key token=abc12345678 lives in the vault.";
    const e = toEntry(en, 0, koLookup({ items: { [entryHash(en)]: { ko: "배포 키 token=abc12345678 은 금고에 있다." } } }));
    expect(e.text).not.toContain("abc12345678");
    expect(e.original).not.toContain("abc12345678");
  });

  it("Hermes 그래프 → 카드에도 한국어가 적용된다", () => {
    const { bot, user } = projectHermesMemory({ memory: [{ source: "memory", body: "Unknown english line." }, { source: "profile", body: EN }] }, lookup);
    expect(user.entries[0].text).toBe(KO);
    expect(bot.entries[0].pending).toBe(true);
  });

  it("검색은 한국어와 영어 원문 둘 다에서 찾는다", () => {
    const card: BotMemoryCard = { key: "k", source: "hermes", name: "기본", subtitle: "", skills: null,
      memory: { state: "ok", chars: 10, approx: true, limit: 100, entries: [toEntry(EN, 0, lookup)], updatedAt: null } };
    expect(visibleCards([card], "all", "합의한 절차", "full")).toHaveLength(1);
    expect(visibleCards([card], "all", "terse korean", "full")).toHaveLength(1);
  });

  it("자동 생성 줄(신원·지식 범위)은 번역 모델 없이 한국어 틀로 보여 준다", () => {
    expect(generatedKo(`I am the Paperclip bot "비서실장" (agent 23dd30d4-9a68-4a5d-83f6-942c4380462d) running on Hermes profile pc-ebb0943f. The owner's requests reach me as Paperclip tasks through the chief of staff (비서실장).`))
      .toBe(`나는 Paperclip 봇 "비서실장"이다(에이전트 23dd30d4, Hermes 프로필 pc-ebb0943f). 사장님 요청은 비서실장을 거쳐 Paperclip 작업으로 들어온다.`);
    expect(generatedKo(`I am the Hermes bot "개발자" (profile uac1c-ubc1c-uc790) working with the owner and other bots in the group chat room "림버스 컴퍼니 헬퍼 개발방".`))
      .toBe(`나는 Hermes 봇 "개발자"이다(프로필 uac1c-ubc1c-uc790). 단체방 "림버스 컴퍼니 헬퍼 개발방"에서 사장님·다른 봇들과 함께 일한다.`);
    expect(generatedKo("My knowledge scopes: common + projects [agent-os, academy]. They are auto-loaded skills (agentos-common, agentos-project-agent-os); generated by AgentOS, never edit them. Save new memory entries in English, one durable fact per entry; AgentOS files them into the right scope later."))
      .toBe("내 지식 범위: 공통 + 프로젝트 [agent-os, academy]. 자동으로 불러오는 스킬(agentos-common, agentos-project-agent-os)로 들어오며 AgentOS가 만든 것이라 직접 고치지 않는다. 새 기억은 영어로, 항목 하나에 사실 하나씩 저장하고 분류는 AgentOS가 나중에 한다.");
    expect(generatedKo("Something else.")).toBeNull();
    expect(koLookup({ items: {} })(`I am the Hermes bot "개발자" (profile x) working with the owner and other bots in the group chat room "방".`)).toContain("단체방");
  });

  it("브라우저 번들에 들어가는 memory.ts 는 knowledge.ts(node:fs)를 값으로 가져오지 않는다", () => {
    const src = readFileSync(new URL("../src/memory.ts", import.meta.url), "utf8");
    const imports = src.split("\n").filter(l => /^import .*knowledge\.js/.test(l));
    expect(imports.length).toBe(1);
    expect(imports.every(l => l.startsWith("import type "))).toBe(true);
  });
});
